### ISSUE TITLE
Role fails when run inside Linux Container (lxc): Failed to reload sysctl: sysctl: setting key "vm.overcommit_memory": Read-only file system

### ISSUE THREAD

**Issue by NHGmaniac** [DavidWittman/ansible-redis#241]
Inside Linux Containers it is not possible to modify Kernel Parameters.
Issue seems to be this task, a quick fix would be adding ignore_errors: true to the task.
https://github.com/DavidWittman/ansible-redis/blob/6362fc1859253b3ac852baeed8ec29272aaa3201/tasks/install.yml#L2-L9

**Comment by Migsi** [comment]
This should be fixed by my [merge request](https://github.com/DavidWittman/ansible-redis/pull/254). Hope @DavidWittman merges this soon.

**Comment by siavashsardari** [comment]
I had the same issue but disabling overcommit_memory did not resolve the issue.I just uploaded a [PR](https://github.com/DavidWittman/ansible-redis/pull/259) 
and also you should disable the protected_mode.

**Comment by TopheC** [comment]
In LXC container in Proxmox same issue happen. [PR](https://github.com/DavidWittman/ansible-redis/pull/259) from @siavashsardari seems to be a good solution.
